
### Define Variables
@port=46565

### call Currency
GET http://localhost:4004/odata/v4/proxy/Currency
Content-Type: application/json

### call AltCostCenter
GET http://localhost:4004/odata/v4/proxy/AltCostCenter
Content-Type: application/json

### call FOCompany
GET http://localhost:4004/odata/v4/proxy/FOCompany
Content-Type: application/json

### call PayGroup
GET http://localhost:4004/odata/v4/proxy/PayGroup
Content-Type: application/json

### call isExpat
GET http://localhost:4004/odata/v4/proxy/isExpat
Content-Type: application/json

### call UOM
GET http://localhost:4004/odata/v4/proxy/UOM(locale='en')
Content-Type: application/json

### call LoggedInUser
GET http://localhost:4004/odata/v4/proxy/LoggedInUser
Content-Type: application/json


### call MassWTList
GET http://localhost:4004/odata/v4/proxy/MassWTList(reqType='IT15')
Content-Type: application/json

### call ApprovalCount
GET http://localhost:4004/odata/v4/proxy/ApprovalCount
Content-Type: application/json

### call isHRAdmin
GET http://localhost:4004/odata/v4/proxy/isHRAdmin
Content-Type: application/json

### call RBPEmployee
GET http://localhost:35805/odata/v4/proxy/getUsersByDynamicGroup?role=HRSITE
Content-Type: application/json

### post OneTimePayHANA 2010
POST http://localhost:4004/odata/v4/proxy/OneTimePayHANA
Content-Type: application/json

{
    "results": [
      {
        "cust_unit": "006",
        "reqchangedByUser": "",
        "country": "FRA",
        "cust_payComponent": "9GX1-FRA-10",
        "createdByUser": "",
        "reqworkflow_id": "",
        "cust_user": "Houria Attaf",
        "cust_paycompvalue": 0,
        "reqforwardSequence": "",
        "createdOn": "",
        "autoApproved": "",
        "cust_userId": "50073660",
        "reqagent": "",
        "reqlastModified": "",
        "cust_notes": "",
        "reqnextAgent": "",
        "effectiveStartDate": "/Date(1733011200000)/",
        "cust_calculatedAmount": "",
        "reqexternalCode": "",
        "reqcreatedOn": "",
        "cust_externalCode": "",
        "initiatorLanguage": "",
        "cust_currencyCode": null,
        "cust_number": "1",
        "reqrequestType": "",
        "cust_customString": "",
        "reqworkflowSequence": "",
        "reqnotificationAgent": "",
        "cust_existingCode": "",
        "reqstatus": "",
        "reqchangedBy": "",
        "createdBy": "",
        "cust_unit_txt": "Pieces (006)",
        "lastModified": "",
        "cust_payComponent_txt": "On Duty Day in the Week",
        "status": "",
        "cust_sequenceNumber": "",
        "cust_alternativeCostCenter": "",
        "cust_alternativeCostCenter_txt": "",
        "specialRecognition": "0",
        "additionalInfo": "",
        "uom": "020",
        "wagetype": "9GX1",
        "isIndEval": 0,
        "isValid": true,
        "delimitIndicator": 0,
        "displayAmount": "",
        "userId": "Houria Attaf(50073660)",
        "role": "8",
        "isAmount": 2,
        "amountEditable": false,
        "currencyEditable": false,
        "numberEditable": true,
        "uomEditable": true
      },
      {
        "cust_unit": "006",
        "reqchangedByUser": "",
        "country": "FRA",
        "cust_payComponent": "9GX4-FRA-10",
        "createdByUser": "",
        "reqworkflow_id": "",
        "cust_user": "Houria Attaf",
        "cust_paycompvalue": 0,
        "reqforwardSequence": "",
        "createdOn": "",
        "autoApproved": "",
        "cust_userId": "50073660",
        "reqagent": "",
        "reqlastModified": "",
        "cust_notes": "",
        "reqnextAgent": "",
        "effectiveStartDate": "/Date(1735689600000)/",
        "cust_calculatedAmount": "",
        "reqexternalCode": "",
        "reqcreatedOn": "",
        "cust_externalCode": "",
        "initiatorLanguage": "",
        "cust_currencyCode": null,
        "cust_number": "2",
        "reqrequestType": "",
        "cust_customString": "",
        "reqworkflowSequence": "",
        "reqnotificationAgent": "",
        "cust_existingCode": "",
        "reqstatus": "",
        "reqchangedBy": "",
        "createdBy": "",
        "cust_unit_txt": "Pieces (006)",
        "lastModified": "",
        "cust_payComponent_txt": "On Duty Public Holiday",
        "status": "",
        "cust_sequenceNumber": "",
        "cust_alternativeCostCenter": "",
        "cust_alternativeCostCenter_txt": "",
        "specialRecognition": "0",
        "additionalInfo": "",
        "uom": "020",
        "wagetype": "9GX4",
        "isIndEval": 0,
        "isValid": true,
        "delimitIndicator": 0,
        "displayAmount": "",
        "userId": "Houria Attaf(50073660)",
        "role": "8",
        "isAmount": 2,
        "amountEditable": false,
        "currencyEditable": false,
        "numberEditable": true,
        "uomEditable": true
      }
    ]
  }

### post OneTimePayHANA 0416
POST http://localhost:4004/odata/v4/proxy/OneTimePayHANA
Content-Type: application/json

{
    "results": [
      {
        "cust_unit": "DAY",
        "reqchangedByUser": "",
        "country": "FRA",
        "cust_payComponent": "39-FRA-16",
        "createdByUser": "",
        "reqworkflow_id": "",
        "cust_user": "Brigitte Neubauer",
        "cust_paycompvalue": 0,
        "reqforwardSequence": "",
        "createdOn": "",
        "autoApproved": "",
        "cust_userId": "59000050",
        "reqagent": "",
        "reqlastModified": "",
        "cust_notes": "vp comment",
        "reqnextAgent": "",
        "effectiveStartDate": "/Date(1735516800000)/",
        "cust_calculatedAmount": "",
        "reqexternalCode": "",
        "reqcreatedOn": "",
        "cust_externalCode": "",
        "initiatorLanguage": "",
        "cust_currencyCode": "EUR",
        "cust_number": "1",
        "reqrequestType": "",
        "cust_customString": "",
        "reqworkflowSequence": "",
        "reqnotificationAgent": "",
        "cust_existingCode": "",
        "reqstatus": "",
        "reqchangedBy": "",
        "createdBy": "",
        "cust_unit_txt": "Days (DAY)",
        "lastModified": "",
        "cust_payComponent_txt": "Holiday quota (expats)",
        "status": "",
        "cust_sequenceNumber": "",
        "cust_alternativeCostCenter": "",
        "cust_alternativeCostCenter_txt": "",
        "specialRecognition": "0",
        "additionalInfo": "",
        "uom": "010",
        "wagetype": "L439",
        "isIndEval": 0,
        "isValid": true,
        "delimitIndicator": 0,
        "displayAmount": "",
        "isAmount": 0,
        "userId": "59000050",
        "role": "8"
      }
    ]
  }


### post AvailabilityHANA 2004
POST http://localhost:4004/odata/v4/proxy/AvailabilityHANA
Content-Type: application/json

{
    "results": [
      {
        "cust_externalCode": "",
        "cust_userId": "59000050",
        "cust_payComponent": "15",
        "effectiveStartDate": "/Date(1733011200000)/",
        "cust_startTime": "07:00:00",
        "cust_endDate": "/Date(1733011200000)/",
        "cust_endTime": "08:00:00",
        "cust_customString": "",
        "cust_notes": "",
        "cust_existingCode": "",
        "status": "",
        "lastModified": "",
        "createdBy": "",
        "createdOn": "",
        "autoApproved": "",
        "createdByUser": "",
        "country": "FRA",
        "initiatorLanguage": "",
        "cust_payComponent_txt": "Astreinte niveau 1 payée",
        "delimitIndicator": 0,
        "cust_dailyWorkSchedule": "",
        "cust_dailyWorkScheduleTxt": "",
        "cust_dwsGrouping": "",
        "cust_dwsGroupingTxt": "",
        "cust_wsVariant": "",
        "cust_wsVariantTxt": "",
        "cust_customVar1": "Brigitte Neubauer",
        "cust_customVar2": "",
        "cust_customVar3": "",
        "cust_customVar4": "",
        "cust_customVar5": "",
        "cust_customVar6": "",
        "reqworkflow_id": "",
        "reqexternalCode": "",
        "reqrequestType": "",
        "reqworkflowSequence": "",
        "reqforwardSequence": "",
        "reqcreatedOn": "",
        "reqstatus": "",
        "reqagent": "",
        "reqnotificationAgent": "",
        "reqnextAgent": "",
        "reqchangedBy": "",
        "reqlastModified": "",
        "userId": "Brigitte Neubauer(59000050)",
        "role": "8",
        "isEndDateEnable": null,
        "wagetype": "15",
        "amountEditable": true,
        "currencyEditable": true,
        "numberEditable": true,
        "uomEditable": true,
        "isValid": true
      }
    ]
  }